server:
  port: 6000
spring:
  application:
    name: company-crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  sion:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka