server:
  port: 5000
spring:
  application:
    name: company-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss: #这里就是阿里云OSS提供的相关的参数配置。
    access-key-id: LTAI4FrkwzQdXia8uvEtgReW
    access-key-secret: NvjZRFpH86GVXSV2cfGWtmXLb90ksJ
    bucket-domain: http://company-crowd-video.oss-cn-shenzhen.aliyuncs.com
    bucket-name: company-crowd-video
    end-point: http://oss-cn-shenzhen.aliyuncs.com
